name: Test Install Script

on:
  workflow_dispatch:

jobs:
  test-unix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux x86_64
          - os: macos-latest
            name: macOS aarch64
          - os: macos-13
            name: macOS x86_64

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install zigup
        run: curl -sSfL https://raw.githubusercontent.com/Satheeshsk369/zigup/main/install.sh | sh

      - name: Install and verify master Zig
        run: |
          $HOME/.local/bin/zigup install master
          $HOME/.local/bin/zigup default master
          $HOME/.local/bin/zigup list
          zig version
        env:
          PATH: ${{ env.HOME }}/.local/bin:${{ env.PATH }}

  test-windows:
    name: Windows x86_64
    runs-on: windows-latest

    steps:
      - name: Install zigup
        shell: pwsh
        run: |
          $script = (Invoke-WebRequest -UseBasicParsing https://raw.githubusercontent.com/Satheeshsk369/zigup/main/install.ps1).Content
          Invoke-Expression $script

      - name: Install and verify master Zig
        shell: pwsh
        run: |
          $env:PATH = "$env:LOCALAPPDATA\zigup\bin;$env:PATH"
          zigup install master
          zigup default master
          zigup list
          zig version
