name: Test Install Script

on:
  workflow_dispatch:

jobs:
  test-unix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux x86_64
          - os: macos-latest
            name: macOS aarch64

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install zigup
        run: |
          curl -sSfL https://raw.githubusercontent.com/Satheeshsk369/zigup/main/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install master Zig
        run: zigup install master

      - name: Set master as default
        run: zigup default master

      - name: Verify
        run: |
          zigup list
          zig version

  test-windows:
    name: Windows x86_64
    runs-on: windows-latest

    steps:
      - name: Install zigup
        shell: pwsh
        run: |
          $script = (Invoke-WebRequest -UseBasicParsing https://raw.githubusercontent.com/Satheeshsk369/zigup/main/install.ps1).Content
          Invoke-Expression $script
          "$env:LOCALAPPDATA\zigup\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Disable Defender for Zig data directory
        shell: pwsh
        run: Add-MpPreference -ExclusionPath "$env:LOCALAPPDATA\zigup"

      - name: Install master Zig
        shell: pwsh
        run: zigup install master

      - name: Set master as default
        shell: pwsh
        run: zigup default master

      - name: Verify
        shell: pwsh
        run: |
          zigup list
          zig version
